hello/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'hello'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('create_profile/', views.create_profile, name='create_profile'),
    path('edit/<int:num>', views.edit, name='edit'),    
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('delete/<int:num>', views.delete, name='delete'),
    path('find/', views.find, name='find'),
    path('plot/', views.get_svg, name='plot'),
    path('all_year/', views.all_year, name='all_year'),
    path('all_users/', views.all_users, name='all_users'),
    path('year_plot/', views.get_bar_svg, name='year_plot'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="hello/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="hello:index"), name='logout'),
]

hello/models.py
import re
from django.db import models
import datetime
from django.urls import reverse
from datetime import datetime as dt
from django.contrib.auth.models import User

now = datetime.datetime.now()
y = now.year
m = now.month
d = now.day
Year_data = [(2018, 2018),(2019, 2019),(2020, 2020),(2021, 2021),(2022, 2022),(2023, 2023),(2024, 2024), (2025, 2025)]
Month_data = [(1,1),(2,2), (3,3),(4,4),(5,5), (6,6),(7,7),(8,8),(9,9),(10,10),(11,11),(12,12)]
Day_data = [(1,1),(2,2),(3,3),(4,4),(5,5),(6,6),(7,7),(8,8),(9,9),(10,10),(11,11),(12,12),(13,13),(14,14),(15,15),(16,16),(17,17),(18,18),(19,19),(20,20),(21,21),(22,22),(23,23),(24,24),(25,25),(26,26),(27,27),(28,28),(29,29),(30,30),(31,31)]

class Study(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    year = models.IntegerField('year', choices=Year_data, default=y)
    month = models.IntegerField('month',choices=Month_data, default=m)
    day = models.IntegerField('day', choices=Day_data, default=d)
    hour = models.FloatField('hour', default=0)
    comment = models.CharField('comment', max_length=250, blank=True)
     
    def __str__(self):
        return  '(' + str(self.year) + '.' + str(self.month) + '.' + str(self.day) + ')'

class Profile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    purpose_data = [
        ('現在の仕事', '現在の仕事'), 
        ('転職', '転職'), 
        ('趣味', '趣味'), 
        ('その他', 'その他')]
    or_continue = [
        ('1', '使用中'),
        ('0', '退会希望'),
    ]
    language = models.CharField('language', max_length=250, blank=True)
    purpose = models.CharField('purpose', choices=purpose_data, max_length=250, blank=False, default=purpose_data[3])
    weekday_study = models.FloatField('weekdays', default=0)
    holiday_study = models.FloatField('holidays', default=0)
    is_private = models.TextField('is_private', max_length=250, blank=True)
    is_continue = models.CharField('is_continue', choices=or_continue, max_length=250, blank=False, default=or_continue[0])
    

hello/forms.py
from django import forms
from.models import Study
from.models import Profile
import datetime
from datetime import datetime as dt
now = datetime.datetime.now()
y = now.year
m = now.month

from django.contrib.auth.models import User

class StudyForm(forms.ModelForm):
    class Meta:
        model = Study
        fields = ['year','month','day','hour', 'comment']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile      
        fields = ['language', 'purpose', 'weekday_study', 'holiday_study', 'is_private', 'is_continue']

class FindForm(forms.Form):
    find_year = forms.IntegerField(label='年', initial=y , required=True)
    find_month = forms.IntegerField(label='月', initial=m, required=False)

class FindYearForm(forms.Form):
    find_year = forms.IntegerField(label='年', initial=y, required=True)


class SignUpForm(forms.Form):
    username = forms.CharField(label='ニックネーム', widget=forms.TextInput)
    enter_password = forms.CharField(label='パスワードを入力', widget=forms.PasswordInput)
    retype_password = forms.CharField(label='パスワードを再入力', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('このユーザー名は既に使われています。')
        return username

    def clean_enter_password(self):
        password = self.cleaned_data.get('enter_password')
        if len(password) < 8:
            raise forms.ValidationError('パスワードは8文字以上である必要があります。')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('enter_password')
        retyped = self.cleaned_data.get('retype_password')
        if password and retyped and (password != retyped):
            self.add_error(None, 'パスワードが違っています。')
        return self.cleaned_data

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('enter_password')
        new_user = User.objects.create_user(username = username)
        new_user.set_password(password)
        new_user.save()

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from .models import Study, Profile, User
from .forms import StudyForm, FindForm, FindYearForm, ProfileForm, SignUpForm
from django.db.models import Q
from django.db.models import Count, Sum, Max
import datetime
from datetime import date
from django.contrib.auth.decorators import login_required
from django.utils import timezone
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt
mpl.use('Agg')
plt.rcParams['font.family'] = 'AppleGothic'
mpl.rcParams['font.family'] = 'AppleGothic'
import io

now = timezone.localtime(timezone.now())
#now = datetime.datetime.now()
now_year = now.year
now_month = now.month
now_day = now.day
today_list = [now_year, now_month, now_day]

@login_required
def index(request):
    global x, y, y_month, z_target
    x = []
    y = []
    y_month = []
    z_target = []
    x.clear()
    y.clear()
    y_month.clear()
    z_target.clear()
    judge = 0
    y_total = 0
    target_total = 0
    total = 0
    study_day = 0
    rate = '0.0 %'
    profile = None
    data = Study.objects.filter(owner=request.user)
    data = data.filter(year=now_year, month=now_month).order_by('day').reverse()
    isprof = Profile.objects.filter(owner=request.user).count()
    if isprof == 1:
        judge = 1

#profileがあるとき
    if isprof == 1:
        x = []
        y = []      
        x.clear()
        y.clear()
        y_month.clear()
        z_target.clear()
        y_month = [0]
        z_target = [0]
        profile = Profile.objects.get(owner=request.user)
        data = Study.objects.filter(owner=request.user)
        data = data.filter(year=now_year, month=now_month).order_by('day').reverse()

        for d in data:
            x.append(d.day)
            y.append(d.hour)
            total += d.hour
            if d.hour > 0:
                study_day += 1

        for i in range(now_day):
            data = Study.objects.filter(owner=request.user)
            if (i+1) in x:
                month_data = data.filter(year=now_year, month=now_month, day=(i+1)).first()

                y_total += month_data.hour

            y_month.append(y_total)
            d = date(now_year, now_month, i+1)
            dd = d.weekday()
            if dd == 5 or dd == 6:
                target_total += profile.holiday_study
            else:
                target_total += profile.weekday_study
            z_target.append(target_total)
        if target_total == 0:
            rate = '0.0 %'
        else:
            rate = str(f'{(y_total / target_total) * 100:,.1f}') + '% '  

    max_hour = str(data.aggregate(Max('hour'))['hour__max'])
    if len(data) == 0:
        max_hour = 0.0
    total_hour = str(f'{total:,.1f}') 
    params = {
        'study_day': study_day,
        'max_hour': max_hour,
        'total_hour': total_hour,
        'today': today_list,
        'profile': profile,
        'target_total': target_total,
        'rate': rate,
        'judge': judge,
        'isprof': isprof,
    }
    return render(request, 'hello/index.html', params)

#グラフ作成
def setPlt(x, y, z_target, y_month):
    plt.figure(figsize=(10, 3), facecolor="#E6FFE9")
    plt.subplots_adjust(wspace=0.25)
    
    plt.subplot(1,2,1)
    plt.bar(x, y, color="coral")
    fsz = 10
    plt.rcParams["font.size"] = fsz
    plt.xlabel('days', fontsize=15)
    plt.ylabel('hour(hr)', fontsize=15)
    plt.grid(True)    
    plt.xlim([0.5, 32])

    plt.subplot(1,2,2)
    plt.plot(z_target, lw=2, label="target", linestyle = "dashed")
    plt.plot(y_month,lw=2.5, label="result", color="coral")
    plt.legend(fontsize=20)
    plt.xlabel('days', fontsize=15)
    plt.ylabel('hour(hr)', fontsize=15)
    plt.xstep = 2
    plt.grid(True)
    plt.xlim([1, 31.5])
    plt.legend(loc=2, fontsize=14)
    plt.ylim(0)

def plt2svg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s

def get_svg(request):
    setPlt(x, y, z_target, y_month) 
    svg = plt2svg()
    plt.cla() 
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response

@login_required
def create(request):
    params = {
        'title': '記録の追加',
        'form': StudyForm(),
    }
    if (request.method == 'POST'):
        obj = Study()
        obj.owner = request.user
        study = StudyForm(request.POST, instance=obj)
        study.save()
        return redirect(to='/hello/')
    return render(request, 'hello/create.html', params)

@login_required
def create_profile(request):
    judge = 0
    isprof = Profile.objects.filter(owner=request.user).count()
    if isprof == 1:
        judge = 1
    if (request.method == 'POST'):
        obj = Profile()
        obj.owner = request.user        
        user_profile = ProfileForm(request.POST, instance=obj)
        user_profile.save()
        return redirect(to='/hello/')  
    params = {
        'title': 'あなたのプロフィール',
        'form': ProfileForm(),
        'judge': judge,
    }         
    return render(request, 'hello/create_profile.html', params)

@login_required
def edit(request, num):
    obj = Study.objects.get(id=num)
    if (request.method == 'POST'):
        study = StudyForm(request.POST, instance=obj)
        study.save()
        return redirect(to='/hello')
    params = {
        'id': num,
        'form': StudyForm(instance=obj),
    }
    return render(request, 'hello/edit.html', params)

@login_required
def edit_profile(request):
    obj = Profile.objects.get(owner=request.user)
    if (request.method == 'POST'):
        profile = ProfileForm(request.POST, instance=obj)
        profile.save()
        return redirect(to='/hello')
    params = {
        'form': ProfileForm(instance=obj),
    }
    return render(request, 'hello/edit_profile.html', params)

@login_required
def delete(request, num):
    study = Study.objects.get(id=num)
    if (request.method == 'POST'):
        study.delete()
        return redirect(to='/hello/find')
    params = {
        'title': '記録の削除',
        'id':num,
        'obj': study,
    }
    return render(request, 'hello/delete.html', params)

x = []
y = []
y_month = []
z_target = []

@login_required
def find(request):
    data = Study.objects.filter(owner=request.user)
    num_data = 0
    month_is = 0
    year=now_year
    if (request.method == 'POST'):
        year_is = 1
        msg = '検索結果'
        form = FindForm(request.POST)
        year = request.POST['find_year']
        data = Study.objects.filter(owner=request.user)
        data = data.filter(year=year).order_by('month', 'day').reverse()
        num_data = len(data)
        if num_data == 0:
            msg = '対象のデータはありません。'

        if request.POST['find_month']:
            form = FindForm(request.POST)
            month = request.POST['find_month']
            data = Study.objects.filter(owner=request.user)
            data = data.filter(month=month).order_by('day')
            num_data = len(data)
            if num_data != 0:
                month_is = 1
                global x, y
                x = []
                y = []
                x.clear()
                y.clear()
                data = Study.objects.filter(owner=request.user)
                data = data.filter(year=year, month=month).order_by('day').reverse()
                for da in data:
                    x.append(da.day)
                    y.append(da.hour) 

            elif num_data == 0:
                msg = '対象のデータはありません。'
                x.clear()
                y.clear()

    else:
        msg = '検索する年と月を入力してください。<br>※1ヶ月の推移を見るには、年、月の両方を入力して下さい。'
        form = FindForm()
        year_is = 0
        data = Study.objects.all().filter(owner=request.user)
        data = data.filter(year=now_year, month=now_month).order_by('day').reverse()

    params = {
        'message': msg,
        'form': form,
        'data': data,
        'num_data': num_data,
        'month_is': month_is,
        'year': year,
        'year_is': year_is,
    }
    return render(request, 'hello/find.html', params)

month_number = []
month_hour = []

@login_required
def all_year(request):
    global month_number, month_hour
    month_hour.clear()

    month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    month_hour = []
    if (request.method == 'POST'):
        msg = '年の勉強時間データ'
        form = FindYearForm(request.POST)
        year = request.POST['find_year']
        year_stat = str(year)

    else:
        msg = '年の勉強時間データ'
        form = FindYearForm()
        year = now_year
        year_stat = '今'
     
    data = Study.objects.filter(owner=request.user)
    year_data = data.filter(year=year)
    for i in range(12):
        total = 0
        for yeardata in year_data.filter(month=i+1):
            total += yeardata.hour
        month_hour.append(total)

    params = {
        'year_stat': year_stat,
        'form': form,
        'message': msg,
    }

    return render(request, 'hello/all_year.html', params)

def bar_setPlt(x, y):
    plt.figure(figsize=(6, 3), facecolor="#E6FFE9")
    plt.bar(x, y)
    plt.title( 'transition', color='#2f4f4f', fontsize=20)
    plt.xlabel('months', fontsize=18)
    plt.ylabel('total hour(hr)', fontsize=18)
    plt.xlim([0.1, 12.5])
    plt.ylim(0.3)
    plt.xticks( np.arange(1, 13, 1) )
    
def bar_plt2svg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s

def get_bar_svg(request):
    bar_setPlt(month_number, month_hour) 
    svg = bar_plt2svg()
    plt.cla() 
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)        
        if form.is_valid():
            form.save()
            return redirect('hello:index')
    else:
        form = SignUpForm()

    context = {'form':form}

hello/templates/hello/all_year.html
{% extends 'hello/base.html' %}

{% block title %}年間の勉強時間{% endblock %}

{% block content %}
<main>
<h2>年間の勉強時間</h2>
<form action="{% url 'hello:all_year' %}" method="post">     
    <table>
        {% csrf_token %}
        {{form}}
        <tr><th></th><td><input type="submit" value="検索開始"></td></tr>
    </table>
</form>

<p>{{message|safe}}</p>
<img src="{% url 'hello:year_plot' %}" width=600 height=350>
</main>
{% endblock %}

hello/templates/hello/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
<header>
    <h1>プログラミングを頑張る人たちのアプリ</h1>
    <div class="head_item logout"><a href= "{% url 'hello:logout' %}">ログアウト</a></div>    
    <div class="head_item"><a href="{% url 'hello:index' %}">ホームへ戻る</a></div>  
</header>
{% block content %}{% endblock %}
</body>
</html>

hello/templates/hello/create.html
{% extends 'hello/base.html' %}

{% block content %}
<main>
<h2 ><span class="under">勉強時間の記録</span></h2>
<p>勉強時間を記録します。<br>※勉強時間は小数点1位まで記録できます。</p>
<table>
    <tr>
        <th>年</th>
        <th>月</th>
        <th>日</th>
        <th>勉強時間(Hr)</th>
        <th>コメント</th>
        <th></th>
    </tr>
    <tr>
        <form action="{% url 'hello:create' %}" method="post">
        {% csrf_token %}        
        <td>{{form.year}}</td>
        <td>{{form.month}}</td>
        <td>{{form.day}}</td>
        <td width="100">{{form.hour}}</td>
        <td>{{form.comment}}</td>
        <td><div class="btn"><input type="submit" value="追加"></div></td>
        </form>
    </tr>    
</table>
</main>
{% endblock %} 

hello/templates/hello/create_profile.html
{% extends 'hello/base.html' %}

{% block content %}

{% if judge == 0 %}
<main>
<h2><span class="under">プロフィールの作成</span></h2>
<p>　あなたのプロフィールを作成します。</p>
<table>
    <form action="{% url 'hello:create_profile' %}" method="post">
        {% csrf_token %}
        <tr>
            <th width="200">使用言語</th>
            <td>{{form.language|safe}}</td>
        </tr>
        <tr>
            <th>勉強の目的</th>
            <td>{{form.purpose|safe}}</td>
        </tr>
        <tr>
            <th>平日の目標勉強時間</th>
            <td>{{form.weekday_study|safe}}</td>
        </tr>
        <tr>
            <th>休日の目標勉強時間</th>
            <td>{{form.holiday_study|safe}}</td>
        </tr>
        <tr>
            <th>コメント<br>※一般に公開されるコメントです。</th>
            <td>{{form.is_private|safe}}</td>
        </tr>
        <tr>
            <th></th>
            <td>{{form.is_continue|safe}}</td>
        </tr>
        <tr>
            <th> → → →</th>
            <td><div class="btn"><input type="submit" value="作成" ></div></td></tr></td>
        </tr>                   
    </form>
</table>
{% endif %}
<h5>※目標勉強時間は、進捗と比較するために必要なので、忘れず入力して下さい。</h5>
<h5>　今月のの目安の勉強時間を算出するために使用します。(ここでは、月-金を平日、土日を休日としています。)</h5>
<div class="is_continue"><p>退会を希望される方は、「使用中」→「退会希望」へ変更して下さい。</p></div>
</main>
{% endblock %} 

hello/templates/hello/delete.html
{% extends 'hello/base.html' %}

{% block title %}削除ページ{% endblock %}

{% block content %}
<main>
<h2><span class="under">勉強記録の削除</span></h2>
<h5>※以下の記録を削除します。</h5>
<table>
    <tr>
        <th>年</th>
        <th>月</th>
        <th>日</th>
        <th>勉強時間(Hr)</th>
        <th></th>
    </tr>
    <tr>
        <td>{{obj.year}}</td>
        <td>{{obj.month}}</td>
        <td>{{obj.day}}</td>
        <td>{{obj.hour}}</td>
        <form action="{% url 'hello:delete' id %}" method="post">
        {% csrf_token %}
        <td><div class="btn"><input type="submit" value="削除実行"></div></td>
    </tr>
    </form>
</table>
</main>
{% endblock %} 

hello/templates/hello/edit.html
{% extends 'hello/base.html' %}

{% block title %}編集ページ{% endblock %}

{% block content %}
<main>
<h2><span class="under">勉強時間記録の編集</span></h2>
<p>勉強時間の記録を変更します。</p>
<table>
    <tr>
        <th>年</th>
        <th>月</th>
        <th>日</th>
        <th>勉強時間(Hr)</th>
        <th>コメント</th>
        <th></th>
    </tr>
    <tr>
        <form action="{% url 'hello:edit' id %}" method="post">
            {% csrf_token %}        
            <td>{{form.year}}</td>
            <td>{{form.month}}</td>
            <td>{{form.day}}</td>
            <td width="100">{{form.hour}}</td>
            <td>{{form.comment}}</td>
            <td><div class="btn"><input type="submit" value="変更"></div></td>
        </form>
    </tr>      
</table>
</main>
{% endblock %} 

hello/templates/hello/find.html
{% extends 'hello/base.html' %}

{% block title %}検索ページ{% endblock %}

{% block content %}
<main>
<h2>勉強記録の検索</h2>
<div class="head_item logout"><a href= "{% url 'hello:all_year' %}">年間の推移を見る</a></div>    
<form action="{% url 'hello:find' %}" method="post">
    {% csrf_token %}
    <table>
        <p>{% if year_is == 1 %}{{year}}年{% endif %}</p>
        <p>{{message|safe}}</p>
        {{form}}
        <tr><th width="60"></th><td><div class="btn"><input type="submit" value="検索開始"></div></td></tr>
    </table>
</form>
</table>
<p>{{data.year}}</p>
    <table>
        <tr>
            {% if num_data != 0 or year_is == 0 %}
            {% if num_data != 0 %}<th>年</th>{% endif %}
            <th>月</th>
            <th>日</th>
            <th>勉強時間(Hr)</th>
            <th>コメント</th>
            <th>編集</th>
            <th>削除</th>
            {% endif %}
        </tr>
        {% for item in data %}
        <tr>
            {% if num_data != 0 %}<td></td>{% endif %}
            <td>{{item.month}}</td>
            <td>{{item.day}}</td>
            <td>{{item.hour}}</td>     
            <td>{{item.comment}}</td>       
            <td><a href="{% url 'hello:edit' item.id %}">◯</a></td>
            <td><a href="{% url 'hello:delete' item.id %}">△</a></td>
        </tr>
        {% endfor %}
    </table>
</main>
{% endblock %} 

hello/templates/hello/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
<header>
    <h1>プログラミングを頑張る人たちのアプリ</h1>
    <div id="today">{{today.0}}/{{today.1}}/{{today.2}}</h2>
    <div class="head_item logout"><a href= "{% url 'hello:logout' %}">ログアウト</a></div>    
    <div class="head_item"><a href="{% url 'hello:index' %}">ホームへ戻る</a></div>
    <div class="head_item"><a href="{% url 'hello:all_users' %}">みんなの記録を見る</a></div>      
</header>

<main>
    <h2>こんにちは、<span class="username">{{user.username}}</span> さん</h2>
    {% if judge == 0 %}<p> ※最初に、右下からプロフィール情報の登録を行ってください。</h2>{% endif %}
    <h3>今月の学習記録</h3>
    <table>
        <tr>
            <th  width="190">勉強した日数</th>
            <td  width="145">{{study_day|safe}}日/ {{today.2|safe}}日</td>
        </tr>
        <tr>
            <th>最大勉強時間</th>
            <td>{{max_hour|safe}} 時間</td>
        </tr>
        <tr>
            <th>勉強時間合計(実績)</th>
            <td>{{total_hour|safe}} 時間</td>
        </tr>
        <tr>
            <th>勉強時間合計(目標)</th>
            <td>{{target_total|safe}} 時間</td>
        </tr>
        <tr>
            <th>勉強時間の達成率</th>
            <td>{{rate|safe}}</td>
        </tr>
        {% if judge == 1 %}
        <tr>
            <th></th>
            <td><a href="{% url 'hello:create' %}" id="study_record">勉強時間を記録</a></td>
        </tr>
        {% endif %}
    </table>
    {% if judge == 1 %}{% if isprof >= 1 %}<div class="img_index"><img src="{% url 'hello:plot' %}" width=800 height=300></div>
    <div id="graph_title">今月の勉強時間の記録　　　　　　　　　　　　　今月の勉強時間の累積</div>{% endif %}{% endif %}

    {% if judge == 1 %}<div class="footer_item"><a href="{% url 'hello:find' %}">勉強の記録を検索</a></div>{% endif %}
    {% if judge == 0 %}<div class="footer_item"><a href="{% url 'hello:create_profile' %}">プロフィール情報を新規登録</a></div>{% endif %}
    {% if judge == 1 %}<div class="footer_item"><a href="{% url 'hello:edit_profile' %}">プロフィール編集</a></div>{% endif %}
</main>    
</body>
</html>

hello/templates/hello/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
<header>
    <h1>プログラミングを頑張っている人たちの勉強時間記録アプリ</h1>
    <div class="head_item"><a href="{% url 'hello:all_users' %}">みんなの記録を見てみる</a></div>         
</header>
<main>
    <h2>☆ログインして下さい。</h2>
    <form action="{% url 'hello:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="btn"><input type="submit" value="ログイン"></div>
    </form>
    <h6></h6>
    <h5>初めての方はログイン後、プロフィール作成を行って下さい。</h5>
    <h5>↓まだアカウントを持っていない場合はこちら</h5>
    <p><div class="login"><a href= "{% url 'hello:signup' %}">アカウント作成</a></div></p>
</main>
</body>
</html>

hello/templates/hello/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>アカウント作成画面</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/css/style.css' %}" />
</head>
<body>
<header>
    <h1>プログラミングを頑張る人たちのアプリ</h1>
    <div class="head_item"><a href="{% url 'hello:all_users' %}">みんなの記録を見る</a></div>      
</header>
<main>
    <h2>ようこそ！！</h2>
    <p>このアプリは、プログラミングを頑張る人たちが、毎日の勉強時間を記録することができるアプリです。<br>自分の記録用としてだけでなく、他のユーザーの当日の勉強時間を見ることが出来ます。<br><div id="first_message">自分以外の人も頑張っているのが見ることが出来、勉強のモチベーションを持続することが出来ます。</div></p>
    <h3><span class="under">アカウントの作成</span></h3>
    <p>※パスワードは、第三者に予測されにくくするため使い回しを避け、大文字、小文字、数字を組み合わせたものを使用して下さい。<br>※↓ニックネームは公開されません。</p>
    {% csrf_token %}
    <form action="{% url 'hello:signup' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="btn">
            <input type="submit" value="アカウント作成">
        </div>
    </form>
    <p>　</p>
    <h5>↓↓既にアカウントをお持ちの方は下からログインして下さい。</h5>
    <p><div class="login"><a href= "{% url 'hello:login' %}">ログイン</a></div></p>
</main>    
</body>
</html>